### ISSUE TITLE
bgpmap error

### ISSUE THREAD

**Issue by XioNoX** [sileht/bird-lg#19]
All the bgpmap queries return the following error in the logs, as well as an "Internal Server Error" on the frontend.

Please let me know if you need more informations.

```
10.68.21.68 - - [12/Jun/2017 21:53:22] "GET /prefix_bgpmap/ESAMS/ipv4?q=118.69.108.0/24 HTTP/1.1" 500 -
[2017-06-12 21:53:28,942] ERROR in app: Exception on /prefix_bgpmap/ESAMS/ipv4 [GET]
Traceback (most recent call last):
  File "/home/birdlg/.local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/birdlg/.local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/birdlg/.local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/birdlg/.local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/birdlg/.local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "lg.py", line 363, in show_route_for_bgpmap
    return show_route("prefix_bgpmap", hosts, proto)
  File "lg.py", line 633, in show_route
    detail[host] = build_as_tree_from_raw_bird_ouput(host, proto, res)
  File "lg.py", line 562, in build_as_tree_from_raw_bird_ouput
    path.extend(line.replace("BGP.as_path:", "").strip().split(" "))
AttributeError: 'NoneType' object has no attribute 'extend'
```

**Comment by acoul** [comment]
I was beaten by the same error in my efforts to convert bird-lg to python3 using 2to3

> Exception on /prefix_bgpmap/aifnis/ipv4 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/extra/var/www/ozo.com/htdocs/cacti/birdlg/lg.py", line 364, in show_route_for_bgpmap
    return show_route("prefix_bgpmap", hosts, proto)
  File "/extra/var/www/ozo.com/htdocs/cacti/birdlg/lg.py", line 641, in show_route
    detail[host] = build_as_tree_from_raw_bird_ouput(host, proto, res)
  File "/extra/var/www/ozo.com/htdocs/cacti/birdlg/lg.py", line 570, in build_as_tree_from_raw_bird_ouput
    path.extend(line.replace("BGP.as_path:", "").strip().split(" "))
AttributeError: 'NoneType' object has no attribute 'extend'
