### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'extend'

### ISSUE THREAD

**Issue by takenek** [sileht/bird-lg#22]
Hello,
When i try generate map for show route for i get this error everytime:

```
AttributeError
AttributeError: 'NoneType' object has no attribute 'extend'

Traceback (most recent call last)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
Open an interactive python shell in this frameresponse = self.handle_exception(e)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/bird-lg-master/lg.py", line 363, in show_route_for_bgpmap
return show_route("prefix_bgpmap", hosts, proto)
File "/opt/bird-lg-master/lg.py", line 633, in show_route
detail[host] = build_as_tree_from_raw_bird_ouput(host, proto, res)
File "/opt/bird-lg-master/lg.py", line 562, in build_as_tree_from_raw_bird_ouput
path.extend(line.replace("BGP.as_path:", "").strip().split(" "))
AttributeError: 'NoneType' object has no attribute 'extend'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```

Best Regards

**Comment by loopodoopo** [comment]
Did you install graphivz?

**Comment by takenek** [comment]
I don`t remember how i change this - but that was a problem with understanding my configuration of BGP routers.
After change config he start working but don`t remember what i change......
Best Regards
