### ISSUE TITLE
bird-2.0.x compatibility

### ISSUE THREAD

**Issue by tamihiro** [sileht/bird-lg#43]
The output format of `show protocols` and `show route` has changed in bird-2.

- bird-1.6.3
```
bird> show protocol
name     proto    table    state  since       info
kernel1  Kernel   master   up     12:37:21    
device1  Device   master   up     12:37:21    
static1  Static   master   up     12:37:21    
v4_9370  BGP      master   up     12:37:26    Established   
v4_9371  BGP      master   up     12:38:27    Established

bird> show route for 8.8.8.8 all
8.8.8.0/24         via 192.168.11.1 on eth2 [v4_9370 12:37:29 from 59.106.1.2] * (100/?) [AS15169i]
	Type: BGP unicast univ
	BGP.origin: IGP
	BGP.as_path: 9370 15169
	BGP.next_hop: 157.17.128.4
	BGP.med: 0
	BGP.local_pref: 100
	BGP.community: (9370,200) (9370,201)
                   via 192.168.11.1 on eth2 [v4_9371 12:38:42 from 210.224.162.177] (100/?) [AS15169i]
	Type: BGP unicast univ
	BGP.origin: IGP
	BGP.as_path: 9371 15169
	BGP.next_hop: 157.17.144.1
	BGP.med: 0
	BGP.local_pref: 100
	BGP.community: (9371,200) (9371,203)
```
- bird-2.0.4
```
bird> show protocols
Name       Proto      Table      State  Since         Info
device1    Device     ---        up     12:46:55.926  
direct1    Direct     ---        down   12:46:55.926  
kernel1    Kernel     master4    up     12:46:55.926  
kernel2    Kernel     master6    up     12:46:55.926  
static1    Static     master4    up     12:46:55.926  
static2    Static     master6    up     12:46:55.926  
rpki1      RPKI       ---        up     12:46:55.932  Established
v4_9370    BGP        ---        up     12:47:00.144  Established   
v4v6_9371  BGP        ---        up     12:47:01.218  Established   
v6_9370    BGP        ---        up     12:47:00.377  Established   

bird> show route for 8.8.8.8 all
Table master4:
8.8.8.0/24           unicast [v4_9370 12:47:02.951 from 59.106.1.2] * (100/?) [AS15169i]
	via 192.168.11.1 on eth2
	Type: BGP univ
	BGP.origin: IGP
	BGP.as_path: 9370 15169
	BGP.next_hop: 157.17.128.4
	BGP.med: 0
	BGP.local_pref: 100
	BGP.community: (9370,200) (9370,201)
                     unicast [v4v6_9371 12:47:18.998 from 210.224.162.177] (100/?) [AS15169i]
	via 192.168.11.1 on eth2
	Type: BGP univ
	BGP.origin: IGP
	BGP.as_path: 9371 15169
	BGP.next_hop: 157.17.144.1
	BGP.med: 0
	BGP.local_pref: 100
	BGP.community: (9371,200) (9371,203)
```
 Please review PR #42, which should parse the output of both old and newer versions of bird.

**Comment by tamihiro** [comment]
I've just noticed #38 did fix parsing the output of `show route summary` but not of `show route for <prefix> all` and therefore `build_as_tree_from_raw_bird_ouput()` fails with exception.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./lg.py", line 369, in show_route_for_bgpmap
    return show_route("prefix_bgpmap", hosts, proto)
  File "./lg.py", line 665, in show_route
    detail[host] = build_as_tree_from_raw_bird_ouput(host, proto, res)
  File "./lg.py", line 594, in build_as_tree_from_raw_bird_ouput
    path.extend(line.replace("BGP.as_path:", "").strip().split(" "))
AttributeError: 'NoneType' object has no attribute 'extend'
```
Please review #45,  which is actually #42 minus the first chunk of diffs.
