### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by takenek** [sileht/bird-lg#64]
Hello
I just update bird-lg to new version and stop working.

[2020-06-13 21:19:21,397] ERROR in app: Exception on /bgpmap/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "lg.py", line 494, in show_bgpmap
    hop_label = hop_label + "*"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

I got version from 2019 year and working perfect with BIRD 1.6.6

**Comment by zorun** [comment]
This pile of code is really hard to debug.

What is the query that triggers this bug?

**Comment by takenek** [comment]
Nothing special just ask about bgp map for 2a00:1450:4001:806::2003/128 i revert version and working good old version.

**Comment by zorun** [comment]
Ok, I could reproduce, it happens when the interface name contains non-alphanumerical characters (e.g. `eth1.945` or `br-foo`). I am fixing this.

**Comment by takenek** [comment]
Hello,
Working good  i just check new patch.
